<?php

namespace Database\Seeders;

use App\Models\Employee ;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Mockery\Undefined;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $personalUAI = 
        [
            [
                'p00' => '155718',
                'cedula' => '11917242',
                'primer_nombre' => 'JENBLUK',
                'segundo_nombre' => null,
                'primer_apellido' => 'VANEGAS',
                'segundo_apellido' => 'GARCIA',
                'cargo_id' => 9,
                'uai_id' => 1,
                'telefono' => '4126625907',
                'gmail' => 'jenblukvanegas@gmail.com',
                'email_cantv' => 'jvane01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155718.jpg',
              ],
              [
                'p00' => '155877',
                'cedula' => '25604428',
                'primer_nombre' => 'KATERINE',
                'segundo_nombre' => 'ENYERLI',
                'primer_apellido' => 'DALESSANDRO',
                'segundo_apellido' => 'RODRIGUEZ',
                'cargo_id' => 1,
                'uai_id' => 1,
                'telefono' => '4126625907',
                'gmail' => 'kdales01.uai@gmail.com',
                'email_cantv' => 'kdales01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155877.jpg',
              ],
              [
                'p00' => '210475',
                'cedula' => '11488022',
                'primer_nombre' => 'LEONARDO',
                'segundo_nombre' => 'ALBERTO',
                'primer_apellido' => 'APONTE',
                'segundo_apellido' => 'RAMOS',
                'cargo_id' => 10,
                'uai_id' => 1,		
                'telefono' => '4124905187',
                'gmail' => 'leonardoaponte781@gmail.com',
                'email_cantv' => 'lapont03@cantv.com.ve',
                'foto_perfil' => '/images/uai/210475.jpg',
              ],
              [
                'p00' => '156286',
                'cedula' => '10519206',
                'primer_nombre' => 'MARTIN',
                'segundo_nombre' => 'HIPOLITO',
                'primer_apellido' => 'GONZALEZ',
                'segundo_apellido' => 'CONTRERAS',
                'cargo_id' => 11,
                'uai_id' => 1,
                'telefono' => '4265161189',
                'gmail' => 'mhgonzalez911@gmail.com',
                'email_cantv' => 'mgonza130@cantv.com.ve',
                'foto_perfil' => '/images/uai/156286.jpg',
              ],
              [
                'p00' => '131466',
                'cedula' => '3970276',
                'primer_nombre' => 'MAGALY',
                'segundo_nombre' => 'CONCEPCION',
                'primer_apellido' => 'VARGAS',
                'segundo_apellido' => null,
                'cargo_id' => 11,
                'uai_id' => 3,
                'telefono' => '4166616633',
                'gmail' => 'mvarga04.uai@gmail.com',
                'email_cantv' => 'mvarga04@cantv.com.ve',
                'foto_perfil' => '/images/uai/131466.jpg',
              ],
              [
                'p00' => '206620',
                'cedula' => '6205113',
                'primer_nombre' => 'JACQUELINE',
                'segundo_nombre' => 'EMILIA',
                'primer_apellido' => 'OLIVERA',
                'segundo_apellido' => 'PARTIDAS',
                'cargo_id' => 7,
                'uai_id' => 9,
                'telefono' => null,
                'gmail' => 'jolive02.uai@gmail.com',
                'email_cantv' => 'jolive02@cantv.com.ve',
                'foto_perfil' => '/images/uai/206620.jpg',
              ],
              [
                'p00' => '124184',
                'cedula' => '11966635',
                'primer_nombre' => 'KEYLA',
                'segundo_nombre' => 'SOLEDAD',
                'primer_apellido' => 'PEREIRA',
                'segundo_apellido' => 'VILLARROEL',
                'cargo_id' => 6,
                'uai_id' => 9,
                'telefono' => '4265103485',
                'gmail' => 'kperei02.uai@gmail.com',
                'email_cantv' => 'kperei02.uai@gmail.com',
                'foto_perfil' => '/images/uai/124184.jpg',
              ],
              [
                'p00' => '155919',	
                'cedula' => '11195984',
                'primer_nombre' => 'INDIRA',
                'segundo_nombre' => 'VIRGINIA',
                'primer_apellido' => 'UZCATEGUI',
                'segundo_apellido' => 'GUZMAN',
                'cargo_id' => 4,
                'uai_id' => 9,
                'telefono' => '4129245197',
                'gmail' => null,
                'email_cantv' => 'iuzcat01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155919.jpg',
              ],
              [
                'p00' => '156483',
                'cedula' => '14276231',
                'primer_nombre' => 'FRANKILN',
                'segundo_nombre' => 'ANTONIO',
                'primer_apellido' => 'RUIZ',
                'segundo_apellido' => null,
                'cargo_id' => 4,
                'uai_id' => 7,
                'telefono' => '4241357637',
                'gmail' => 'faruiz01.uai@gmail.com',
                'email_cantv' => 'fruiz01@cantv.com.ve',
                'foto_perfil' => '/images/uai/156483.jpg',
              ],
              [
                'p00' => '155918',
                'cedula' => '19294541',
                'primer_nombre' => 'ISMAEL',
                'segundo_nombre' => 'ENRIQUE',
                'primer_apellido' => 'ARIAS',
                'segundo_apellido' => 'CORDOBA',
                'cargo_id' => 5,
                'uai_id' => 7,
                'telefono' => '4125678269',
                'gmail' => null,
                'email_cantv' => 'iarias01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155918.jpg',
              ],
              [
                'p00' => '132484',
                'cedula' => '6721159',
                'primer_nombre' => 'LUISA',
                'segundo_nombre' => 'ARGELIA',
                'primer_apellido' => 'ARIAS',
                'segundo_apellido' => 'RIERA',
                'cargo_id' => 8,
                'uai_id' => 3,
                'telefono' => '4166114416',
                'gmail' => null,
                'email_cantv' => 'larias02@cantv.com.ve',
                'foto_perfil' => '/images/uai/132484.jpg',
              ],
              [
                'p00' => '155485',
                'cedula' => '12831916',
                'primer_nombre' => 'YUBISAY',
                'segundo_nombre' => 'DEL VALLE',
                'primer_apellido' => 'SALAS',
                'segundo_apellido' => 'PEREZ',
                'cargo_id' => 12,
                'uai_id' => 3,
                'telefono' => '4129953995',
                'gmail' => null,
                'email_cantv' => 'ysalas03@cantv.com.ve',
                'foto_perfil' => '/images/uai/155485.jpg',
              ],
              [
                'p00' => '150389',
                'cedula' => '19512503',
                'primer_nombre' => 'JOHANNA',
                'segundo_nombre' => 'LISBETH',
                'primer_apellido' => 'MEJIAS',
                'segundo_apellido' => 'HERNANDEZ',
                'cargo_id' => 7,
                'uai_id' => 6,
                'telefono' => '4265338738',
                'gmail' => 'jmejia12.uai@gmail.com',
                'email_cantv' => 'jmejia12@cantv.com.ve',
                'foto_perfil' => '/images/uai/150389.jpg',
              ],
              [
                'p00' => '155501',
                'cedula' => '5223346',
                'primer_nombre' => 'ELIZABETH',
                'segundo_nombre' => null,
                'primer_apellido' => 'PEREZ',
                'segundo_apellido' => 'ARANGUREN',
                'cargo_id' => 4,
                'uai_id' => 6,
                'telefono' => '4166531728',
                'gmail' => 'eperez.uai@gmail.com',
                'email_cantv' => 'eperez53@cantv.com.ve',
                'foto_perfil' => '/images/uai/155501.jpg',
              ],
              [
                'p00' => '206397',
                'cedula' => '10381685',
                'primer_nombre' => 'ZENOBIO',
                'segundo_nombre' => null,
                'primer_apellido' => 'OROPEZA',
                'segundo_apellido' => 'SALAZAR',
                'cargo_id' => 3,
                'uai_id' => 6,
                'telefono' => '4166229474',
                'gmail' => 'zorope.uai@gmail.com',
                'email_cantv' => 'zorope@cantv.com.ve',
                'foto_perfil' => '/images/uai/206397.jpg',
              ],[
                'p00' => '146196',
                'cedula' => '10584414',
                'primer_nombre' => 'MARIA',
                'segundo_nombre' => 'ANDREA',
                'primer_apellido' => 'SORATE',
                'segundo_apellido' => 'DE VOLCANES',
                'cargo_id' => 7,
                'uai_id' => 5,
                'telefono' => '4142582181',
                'gmail' => 'masorate01.uai@gmail.com',
                'email_cantv' => 'msorat01@cantv.com.ve',
                'foto_perfil' => '/images/uai/146196.jpg',
              ],
              [
                'p00' => '155435',
                'cedula' => '14008430',
                'primer_nombre' => 'EDUARDO',
                'segundo_nombre' => 'JOSE',
                'primer_apellido' => 'CUMANA',
                'segundo_apellido' => 'CUMANA',
                'cargo_id' => 4,
                'uai_id' => 5,
                'telefono' => '4125771270',
                'gmail' => 'ecumana01.uai@gmail.com',
                'email_cantv' => 'ecuman01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155435.jpg',
              ],
              [
                'p00' => '149057',
                'cedula' => '5969179',
                'primer_nombre' => 'LUISANA',
                'segundo_nombre' => 'YASMIRA',
                'primer_apellido' => 'BARRETO',
                'segundo_apellido' => 'QUIÑONES',
                'cargo_id' => 3,
                'uai_id' => 5,
                'telefono' => '4241950669',
                'gmail' => 'lbarre04.uai@gmail.com',
                'email_cantv' => 'lbarret04@cantv.com.ve',
                'foto_perfil' => '/images/uai/149057.jpg',
              ],
              [
                'p00' => '132129',
                'cedula' => '6810760',
                'primer_nombre' => 'SILVIA',
                'segundo_nombre' => 'ROSA',
                'primer_apellido' => 'VARGAS',
                'segundo_apellido' => 'ORTIZ',
                'cargo_id' => 7,
                'uai_id' => 4,
                'telefono' => '4166209208',
                'gmail' => 'svarga04.uai@gmail.com',
                'email_cantv' => 'svarga04@cantv.com.ve',
                'foto_perfil' => '/images/uai/132129.jpg',
              ],
              [
                'p00' => '124502',
                'cedula' => '10347228',
                'primer_nombre' => 'JOSE',
                'segundo_nombre' => 'ENRIQUE',
                'primer_apellido' => 'VAZQUEZ',
                'segundo_apellido' => 'BASTIDAS',
                'cargo_id' => 4,
                'uai_id' => 4,
                'telefono' => '4166327610',
                'gmail' => 'jvazqu01.uai@gmail.com',
                'email_cantv' => 'jvazqu01@cantv.com.ve',
                'foto_perfil' => '/images/uai/124502.jpg',
              ],
              [
                'p00' => '146236',
                'cedula' => '13138186',
                'primer_nombre' => 'MARIFRANCY',
                'segundo_nombre' => null,
                'primer_apellido' => 'FALCON',
                'segundo_apellido' => 'OLIVAR',
                'cargo_id' => 4,
                'uai_id' => 4,
                'telefono' => '4163054088',
                'gmail' => 'mariolivar.uai@gmail.com',
                'email_cantv' => 'mfalco01@cantv.com.ve',
                'foto_perfil' => '/images/uai/146236.jpg',
              ],
              [
                'p00' => '155267',
                'cedula' => '17300607'	,
                'primer_nombre' => 'FRERYDA',
                'segundo_nombre' => 'MARIBELL',
                'primer_apellido' => 'BETANCOURT',
                'segundo_apellido' => 'FELIX'	,
                'cargo_id' => 3,
                'uai_id' => 4,
                'telefono' => '4143090015',
                'gmail' => 'fbetac.uai@gmail.com',
                'email_cantv' => 'fbetan03@cantv.com.ve',
                'foto_perfil' => '/images/uai/155267.jpg',
              ],
              [
                'p00' => '149382',
                'cedula' => '10054313',
                'primer_nombre' => 'ANA',
                'segundo_nombre' => 'IVONNE',
                'primer_apellido' => 'ROJAS',
                'segundo_apellido' => 'DE RAMOS',
                'cargo_id' => 2,
                'uai_id' => 4,
                'telefono' => '4164583729',
                'gmail' => 'ivonnerojas07.uai@gmail.com',
                'email_cantv' => 'arojas28@cantv.com.ve',
                'foto_perfil' => '/images/uai/149382.jpg',
              ],
              [
                'p00' => '156499',
                'cedula' => '30769416',
                'primer_nombre' => 'PIER',
                'segundo_nombre' => 'LUIGI',
                'primer_apellido' => 'BOLECH',
                'segundo_apellido' => 'DIAZ',
                'cargo_id' => 2,
                'uai_id' => 4,
                'telefono' => '4164583729',
                'gmail' => 'pbolec01.uai@gmail.com'	,
                'email_cantv' => 'pbolec01@cantv.com.ve',
                'foto_perfil' => '/images/uai/156499.jpg',
              ],
              [
                'p00' => '156373',
                'cedula' => '28563229',
                'primer_nombre' => 'GEFERSON',
                'segundo_nombre' => 'LEONAIKER',
                'primer_apellido' => 'MORENO',
                'segundo_apellido' => 'PALACIOS',
                'cargo_id' => 2,
                'uai_id' => 4,
                'telefono' => '4129915401',
                'gmail' => 'gmoren02.uai@gmaill.com',
                'email_cantv' => 'gmoren02@cantv.com.ve',
                'foto_perfil' => '/images/uai/156373.jpg',
              ],
              [
                'p00' => '134363',
                'cedula' => '12398193',
                'primer_nombre' => 'JENY',
                'segundo_nombre' => 'DEL VALLE',
                'primer_apellido' => 'RADA',
                'segundo_apellido' => 'SALAZAR',
                'cargo_id' => 7,
                'uai_id' => 7,
                'telefono' => '4166337594',
                'gmail' => 'jradas01.uai@gmail.com',
                'email_cantv' => 'jradas01@cantv.com.ve',
                'foto_perfil' => '/images/uai/134363.jpg',
              ],
              [
                'p00' => '149070',
                'cedula' => '6559279',
                'primer_nombre' => 'JOSE',
                'segundo_nombre' => 'LUIS',
                'primer_apellido' => 'VILLEGAS',
                'segundo_apellido' => 'HERRERA',
                'cargo_id' => 4,
                'uai_id' => 7,
                'telefono' => '4149893742',
                'gmail' => 'jville12.uai@gmail.com',
                'email_cantv' => 'jville12@cantv.com.ve',
                'foto_perfil' => '/images/uai/149070.jpg',
              ],
              [
                'p00' => '154423',
                'cedula' => '14446916',
                'primer_nombre' => 'ISMIR',
                'segundo_nombre' => 'ROSALIA',
                'primer_apellido' => 'RUMBOS',
                'segundo_apellido' => 'AGUIAR',
                'cargo_id' => 4,
                'uai_id' => 7,
                'telefono' => '4164022312',
                'gmail' => 'irumbos.uai@gmail.com',
                'email_cantv' => 'irumbo01@cantv.com.ve',
                'foto_perfil' => '/images/uai/154423.jpg',
              ],
              [
                'p00' => '150770',
                'cedula' => '14309185',
                'primer_nombre' => 'YERLIN',
                'segundo_nombre' => 'LORENA',
                'primer_apellido' => 'CASTELLANOS',
                'segundo_apellido' => 'RODRIGUEZ',
                'cargo_id' => 3,
                'uai_id' => 7,
                'telefono' => null,
                'gmail' => null,
                'email_cantv' => 'ycaste01@cantv.com.ve',
                'foto_perfil' => '',
              ],
              [
                'p00' => '150753',
                'cedula' => '14157605',
                'primer_nombre' => 'JOHAN',
                'segundo_nombre' => 'RAMON',
                'primer_apellido' => 'INFANTE',
                'segundo_apellido' => 'VANEGAS',
                'cargo_id' => 3,
                'uai_id' => 7,
                'telefono' => '4263188810',
                'gmail' => 'jinfan03.uai@gmail.com',
                'email_cantv' => 'jinfan03@cantv.com.ve',
                'foto_perfil' => '/images/uai/150753.jpg',
              ],
              [
                'p00' => '149073',
                'cedula' => '6548966',
                'primer_nombre' => 'FLOR',
                'segundo_nombre' => 'YSMELDA',
                'primer_apellido' => 'SERRANO',
                'segundo_apellido' => 'MENDOZA',
                'cargo_id' => 3,
                'uai_id' => 7,
                'telefono' => '4262386802',
                'gmail' => 'sflory01.uai@gmail.com',
                'email_cantv' => 'sflory01@cantv.com.ve',
                'foto_perfil' => '/images/uai/149073.jpg',
              ],
              [
                'p00' => '155005',
                'cedula' => '14453673',
                'primer_nombre' => 'RUTH',
                'segundo_nombre' => 'BELINDA',
                'primer_apellido' => 'GOMEZ',
                'segundo_apellido' => 'GARCIA',
                'cargo_id' => 3,
                'uai_id' => 7,
                'telefono' => '4263188810',
                'gmail' => 'rgome01.uai@gmail.com',
                'email_cantv' => 'rgome01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155005.jpg',
              ],
              [
                'p00' => '147987',
                'cedula' => '6326725',
                'primer_nombre' => 'MARIA NICOLINA',
                'segundo_nombre' => 'NELLA',
                'primer_apellido' => 'DE MARINIS',
                'segundo_apellido' => 'BAGNOLI',
                'cargo_id' => 7,
                'uai_id' => 8,
                'telefono' => '4241264891',
                'gmail' => 'mdemar02.uai@gmail.com',
                'email_cantv' => 'mdemar01@cantv.com.ve',
                'foto_perfil' => '/images/uai/147987.jpg',
              ],
              [
                'p00' => '155892',
                'cedula' => '14197937',
                'primer_nombre' => 'ADRIANA',
                'segundo_nombre' => 'CRISTINA',
                'primer_apellido' => 'LINARES',
                'segundo_apellido' => 'CASTILLO',
                'cargo_id' => 12,
                'uai_id' => 8,
                'telefono' => '4148518981',
                'gmail' => 'adrianaclinaresc@gmail.com',
                'email_cantv' => 'alinar09@cantv.com.ve',
                'foto_perfil' => '/images/uai/155892.jpg',
              ],
              [
                'p00' => '155909',
                'cedula' => '15805516',
                'primer_nombre' => 'RUBEN',
                'segundo_nombre' => 'DARIO',
                'primer_apellido' => 'TORRES',
                'segundo_apellido' => 'DUQUE',
                'cargo_id' => 12,
                'uai_id' => 8,
                'telefono' => '4142683382',
                'gmail' => 'rtorre26.uai@gmail.com',
                'email_cantv' => 'rtorre26@cantv.com.ve',
                'foto_perfil' => '/images/uai/155909.jpg',
              ],
              [
                'p00' => '155901',
                'cedula' => '15805515',
                'primer_nombre' => 'BETHZABETH',
                'segundo_nombre' => 'NATHALIE',
                'primer_apellido' => 'ZAMBRANO',
                'segundo_apellido' => 'MENDOZA',
                'cargo_id' => 12,
                'uai_id' => 8,
                'telefono' => '4144543386',
                'gmail' => 'bzambr01.uai@gmail.com',
                'email_cantv' => 'bzambr01@cantv.com.ve',
                'foto_perfil' => '/images/uai/155901.jpg',
              ],
              [
                'p00' => '156642',
                'cedula' => '6901860',
                'primer_nombre' => 'DOUGLAS',
                'segundo_nombre' => 'RAÚL',
                'primer_apellido' => 'SEQUERA',
                'segundo_apellido' => 'SANTANA',
                'cargo_id' => 4,
                'uai_id' => 5,
                'telefono' => '4149100645',
                'gmail' => 'barre04.uai@gmail.com',
                'email_cantv' => 'barre04@cantv.com.ve',
                'foto_perfil' => '/images/uai/156642.jpg',
              ],
              [
                'p00' => '156560',
                'cedula' => '3935574',
                'primer_nombre' => 'LIGIA',
                'segundo_nombre' => null,
                'primer_apellido' => 'RAMIREZ',
                'segundo_apellido' => 'RAMOS',
                'cargo_id' => 8,
                'uai_id' => 2,
                'telefono' => '4143944955',
                'gmail' => 'lramir17.uai@gmail.com',
                'email_cantv' => 'lramir17@cantv.com.ve',
                'foto_perfil' => '/images/uai/156560.jpg',
              ],
              [
                'p00' => '126645',
                'cedula' => '18220808',
                'primer_nombre' => 'ORIANA',
                'segundo_nombre' => 'NAKARELY',
                'primer_apellido' => 'LOPEZ',
                'segundo_apellido' => 'ALESSANDRINI',
                'cargo_id' => 4,
                'uai_id' => 1,
                'telefono' => '4265320101',
                'gmail' => 'olopez01.uai@gmail.com',
                'email_cantv' => 'olopez01@cantv.com.ve',
                'foto_perfil' => '/images/uai/126645.jpg',
              ],
              [
                'p00' => '156646',
                'cedula' => '14758766',
                'primer_nombre' => 'DAYANNA',
                'segundo_nombre' => 'DUGIN',
                'primer_apellido' => 'DURÁN',
                'segundo_apellido' => 'GONZÁLEZ',
                'cargo_id' => 3,
                'uai_id' => 5,
                'telefono' => '4163848415',
                'gmail' => 'dduran03.uai@gmail.com',
                'email_cantv' => 'dduran03@cantv.com.ve',
                'foto_perfil' => '/images/uai/156646.jpg',
              ],
        ];

        
        foreach($personalUAI as $personal)
        {
            $personalUai = new Employee();
            $personalUai->cedula = $personal['cedula'];
            $personalUai->primer_nombre = $personal['primer_nombre'];
            $personalUai->segundo_nombre = $personal['segundo_nombre'] != null ? $personal['segundo_nombre'] : null;
            $personalUai->primer_apellido = $personal['primer_apellido'];
            $personalUai->segundo_apellido = $personal['segundo_apellido'] != null ? $personal['segundo_apellido'] : null;
            $personalUai->telefono = $personal['telefono'];
            $personalUai->p00 = $personal['p00']; 
            $personalUai->gmail = $personal['gmail'] != null ? $personal['gmail'] : null;
            $personalUai->email_cantv = $personal['email_cantv'];
            $personalUai->cargo_id = $personal['cargo_id'];
            $personalUai->uai_id = $personal['uai_id'];
            $personalUai->foto_perfil = isset($personal['foto_perfil']) ? $personal['foto_perfil']: null;
            // $personalUai->user_id = $personal['user_id'];
            $personalUai->save();
        }
    }
}
